# Render Blueprint for Quizda Application
# This file defines all services needed for deployment

services:
  # Backend API Service
  - type: web
    name: quizda-backend
    runtime: node
    region: oregon
    plan: free
    branch: main
    rootDir: server
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
      - key: NEON_DATABASE_URL
        sync: false
      - key: MONGODB_ATLAS_URL
        sync: false
      - key: MONGODB_DBNAME
        value: quizda
      - key: CLIENT_URL
        value: https://quizda.onrender.com

  # Frontend Static Site
  - type: web
    name: quizda-frontend
    runtime: static
    branch: main
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://quizda-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
